# Generated by Django 5.2.5 on 2026-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptionrequest',
            old_name='mobile_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='legal_doc',
            field=models.FileField(blank=True, null=True, upload_to='adoption_docs/'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='photo_id',
            field=models.FileField(blank=True, null=True, upload_to='adoption_docs/'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='selfie_with_pet',
            field=models.ImageField(blank=True, null=True, upload_to='adoption_docs/'),
        ),
    ]
