# Generated by Django 5.2.5 on 2026-04-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_mobile_number_adoptionrequest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Explain why the request was rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='current_pet',
            field=models.CharField(blank=True, default='None', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='experience',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='housing_type',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='landlord_permission',
            field=models.CharField(blank=True, default='House', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='occupation',
            field=models.CharField(default='Student', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='own_or_rent',
            field=models.CharField(default='Own', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='photo_id',
            field=models.FileField(default='default.jpg', upload_to='adoption_docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='previous_pet',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='reason',
            field=models.TextField(default='No reason provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='selfie_with_pet',
            field=models.FileField(blank=True, null=True, upload_to='adoption_docs/'),
        ),
    ]
