# Generated by Django 5.2.5 on 2026-04-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adoptionrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='legal_doc',
            field=models.FileField(default='default_doc.pdf', upload_to='adoption_docs/'),
            preserve_default=False,
        ),
    ]
