# Generated by Django 5.2.5 on 2026-04-22 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pet_created_at_pet_is_special_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
